from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path


def _utc_today() -> str:
    return datetime.now(timezone.utc).date().isoformat()


def ensure_activity_repo_readme(repo_path: Path) -> tuple[Path, bool]:
    """
    Ensure the target *activity report repo* has a README.md.

    - Does not overwrite an existing README.md.
    - Content is client-facing: explains what this repo is and what it contains.
    """
    readme_path = repo_path / "README.md"
    if readme_path.exists():
        return readme_path, False

    text = "\n".join(
        [
            "# Prolific: Git Active — Activity Repo",
            "",
            "This is a repo that shows my coding activity, even if the activity is not pushed to GitHub.",
            "",
            "This repository is intentionally **not** a source-code project.",
            "",
            "Its purpose is to store **anonymized work-activity reports** generated by the",
            "**Prolific: Git Active** background app.",
            "",
            "## What this repo contains",
            "- `reports/`: timestamped JSON + Markdown summaries (aggregates only)",
            "- `docs/`: a small static site (GitHub Pages) that renders a timeline bubblemap",
            "- `viz/`: a local copy of the same bubblemap assets",
            "",
            "## Turn on GitHub Pages (to view the bubblemap)",
            "1. On GitHub, open this repo → **Settings** → **Pages**.",
            "2. Under **Build and deployment**:",
            "   - Source: **Deploy from a branch**",
            "   - Branch: `main` (or your chosen branch)",
            "   - Folder: **/docs**",
            "3. Save. After it deploys, the bubblemap will be available at your repo’s Pages URL.",
            "",
            "## Privacy",
            "- The generator **never reads file contents**.",
            "- Reports are based on **file metadata only** (size/mtime/extensions).",
            "- Reports contain **no file names or paths**—only totals and estimates.",
            "",
            "## Why this exists",
            "Sometimes work happens locally, in private repos, or in testing branches that",
            "never get pushed. This repo provides a lightweight public/private timeline of",
            "activity so contribution history doesn't miss days due to workflow realities.",
            "",
            f"_Created automatically on {_utc_today()}._",
            "",
        ]
    )
    readme_path.write_text(text, encoding="utf-8")
    return readme_path, True


